
# the discord token the bot uses to log in.  You'll need to change this.
token = "aoeu.id.htns"

# the prefix to call bot commands with
prefix = "%"

# the emoji to indicate it's searching history for stuff
# if you want it to be an animated emoji, follow the format "a:emoji_name:emoji_id" (the id might be tricky to get)
# like "a:loading:567758532875911169"
loadingemoji = "🔄"

# tell the bot to load up data.py when it starts
extensions = ["data"]

# the color gradients to use for the graphs
# for more info and options, see https://matplotlib.org/tutorials/colors/colormaps.html
# the number of colormaps specified here is how many channels will be graphed
colormaps = ["Reds_r", "YlOrBr_r", "Greens_r", "Blues_r", "Purples_r", "cividis"]
