
# the discord token the bot uses to log in.  You'll need to change this.
token = "aoeu.id.htns"

# the prefix to call bot commands with
prefix = "%"

# the emoji to indicate it's searching history for stuff
# if you want it to be an animated emoji, follow the format "a:emoji_name:emoji_id" (the id might be tricky to get)
# like "a:loading:567758532875911169"
loadingemoji = "🔄"

# tell the bot to load up data.py when it starts
extensions = ["data", "channel_listener", "reaction_listener", "apod", "db", "markov", "utilities"]

# the color gradients to use for the graphs
# for more info and options, see https://matplotlib.org/tutorials/colors/colormaps.html
# the number of colormaps specified here is how many channels will be graphed
colormaps = ["Reds_r", "YlOrBr_r", "Greens_r", "Blues_r", "Purples_r", "cividis"]

# NASA API token, for APOD stuff if you want
nasatoken = ""

# the channel id for where the bot should post NASA's Astronomy Photo Of the Day
# You'll need to change this to make it work.
apod_channel = 325354209673216010

# the channel id where it should akwardly log if something goes wrong with posting the APOD
apod_err_channel = 500896262351093761

# the hour (local time) that the apod should be about posted at (24hr time)
apod_post_hour = 4

# username and password to postgresql database.  It's assumed you have a database called 'discord'
postgresuser = "postgres"
postgrespwd = ""