
# the discord token the bot uses to log in.  You'll need to change this.
token = "aoeu.id.htns"

# the prefix to call bot commands with
prefix = "%"

# the emoji to indicate it's searching history for stuff
# if you want it to be an animated emoji, follow the format "a:emoji_name:emoji_id" (the id might be tricky to get)
# like "a:loading:567758532875911169"
loadingemoji = "🔄"

# tell the bot to load up data.py when it starts
extensions = ["data", "channel_listener", "reaction_listener", "apod", "db", "markov", "utilities", "minesweeper"]

# the color gradients to use for the graphs
# for more info and options, see https://matplotlib.org/tutorials/colors/colormaps.html
# the number of colormaps specified here is how many channels will be graphed
colormaps = ["Reds_r", "YlOrBr_r", "Greens_r", "Blues_r", "Purples_r", "cividis"]

# username and password to postgresql database.  It's assumed you have a database called 'discord'
postgresuser = "postgres"
postgrespwd = ""


[APOD]
# NASA API token, for APOD stuff if you want
nasatoken = ""

# the channel id for where the bot should post NASA's Astronomy Photo Of the Day
# You'll need to change this to make it work.
apod_channel = 325354209673216010

# the channel id where it should akwardly log if something goes wrong with posting the APOD
apod_err_channel = 500896262351093761

# the hour (local time) that the apod should be about posted at (24hr time)
apod_post_hour = 4


[SHEETS]
spreadsheet = "foo-barbaz"  # spreadsheet id to upload user data to
staff = 392867548414083072  # id of Staff roll
lowest_xp_roll = 396440356239048709  # id of the lowest xp roll
# rolls in between these two are assumed to be just xp ones
highest_xp_roll = 529851477078835200  # id of the highest xp roll
almost_basic_roll = 471839310816215051  # id of xp roll just above the basic one
basic_roll = 391756481772388352  # id of basic roll
lowest_on_topic = 448243063144448015  # id of the lowest on-topic channel in the guild

[TATTLER]
dontlog = [302050872383242240, 212681528730189824]  # disboard and discordlisting.me
mee6 = 159985870458322944
verification = 587745778320277517 # verification channel